debug:
  mode: false
  annotated: true
detection:
  model_path: models/with_mounting_dark.pt
  confidence_threshold: 0.6
  target_class: 0
storage:
  base_path: data
  save_dir: data/images
  save_annotated_image: false
notification:
  cooldown: 40
logging:
  file: logs/system.log
  level: INFO
